-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.bookings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text,
  email text,
  phone text,
  date date,
  time text,
  duration integer DEFAULT 30,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bookings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.contacts (
  id integer NOT NULL DEFAULT nextval('contacts_id_seq'::regclass),
  user_id uuid,
  name text NOT NULL,
  email text NOT NULL,
  phone text,
  company text,
  budget text CHECK (budget = ANY (ARRAY['1000-2000'::text, '2000-4000'::text, '4000-8000'::text, '8000+'::text])),
  service_interest text,
  message text NOT NULL,
  status text DEFAULT 'new'::text CHECK (status = ANY (ARRAY['new'::text, 'read'::text, 'replied'::text, 'converted'::text, 'archived'::text])),
  admin_notes text,
  replied_at timestamp with time zone,
  source text DEFAULT 'website'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contacts_pkey PRIMARY KEY (id),
  CONSTRAINT contacts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.customer_info (
  id integer NOT NULL DEFAULT nextval('customer_info_id_seq'::regclass),
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text NOT NULL,
  phone text,
  company text,
  address text NOT NULL,
  postal_code text NOT NULL,
  city text NOT NULL,
  country text DEFAULT 'FR'::text,
  project_details text,
  newsletter boolean DEFAULT false,
  payment_method text,
  stripe_session_id text,
  order_items jsonb DEFAULT '[]'::jsonb,
  subtotal numeric,
  discount numeric,
  tax numeric,
  total numeric,
  promo_code text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'paid'::text, 'cancelled'::text, 'refunded'::text])),
  ip_address text,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customer_info_pkey PRIMARY KEY (id)
);
CREATE TABLE public.invoices (
  id integer NOT NULL DEFAULT nextval('invoices_id_seq'::regclass),
  order_id integer NOT NULL,
  user_id uuid,
  invoice_number text NOT NULL UNIQUE,
  subtotal numeric NOT NULL,
  tax_rate numeric DEFAULT 20.00,
  tax_amount numeric NOT NULL,
  total numeric NOT NULL,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'sent'::text, 'paid'::text, 'overdue'::text, 'cancelled'::text])),
  due_date date,
  paid_at timestamp with time zone,
  pdf_path text,
  notes text,
  billing_name text,
  billing_address text,
  billing_city text,
  billing_postal_code text,
  billing_country text DEFAULT 'France'::text,
  billing_vat_number text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT invoices_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.newsletter_subscribers (
  id integer NOT NULL DEFAULT nextval('newsletter_subscribers_id_seq'::regclass),
  email text NOT NULL UNIQUE,
  name text,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'unsubscribed'::text, 'bounced'::text])),
  subscribed_at timestamp with time zone DEFAULT now(),
  unsubscribed_at timestamp with time zone,
  source text DEFAULT 'website'::text,
  CONSTRAINT newsletter_subscribers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.order_items (
  id integer NOT NULL DEFAULT nextval('order_items_id_seq'::regclass),
  order_id integer NOT NULL,
  service_id integer,
  service_name text NOT NULL,
  quantity integer DEFAULT 1,
  unit_price numeric NOT NULL,
  total_price numeric NOT NULL,
  custom_options jsonb DEFAULT '{}'::jsonb,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_items_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id)
);
CREATE TABLE public.orders (
  id integer NOT NULL DEFAULT nextval('orders_id_seq'::regclass),
  user_id uuid,
  order_number text NOT NULL UNIQUE,
  total_amount numeric NOT NULL DEFAULT 0.00,
  discount_amount numeric DEFAULT 0.00,
  tax_amount numeric DEFAULT 0.00,
  final_amount numeric NOT NULL DEFAULT 0.00,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text, 'refunded'::text])),
  payment_status text DEFAULT 'pending'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'paid'::text, 'partial'::text, 'refunded'::text, 'failed'::text])),
  payment_method text,
  payment_reference text,
  notes text,
  admin_notes text,
  project_start_date date,
  project_end_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  name text,
  phone text,
  company text,
  role text DEFAULT 'client'::text CHECK (role = ANY (ARRAY['client'::text, 'admin'::text, 'superadmin'::text])),
  avatar_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.projects (
  id integer NOT NULL DEFAULT nextval('projects_id_seq'::regclass),
  order_id integer,
  user_id uuid,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  client_name text,
  project_type text DEFAULT 'vitrine'::text CHECK (project_type = ANY (ARRAY['vitrine'::text, 'ecommerce'::text, 'surmesure'::text, 'autre'::text])),
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'in_progress'::text, 'review'::text, 'completed'::text, 'published'::text])),
  thumbnail text,
  images jsonb DEFAULT '[]'::jsonb,
  technologies jsonb DEFAULT '[]'::jsonb,
  url text,
  is_portfolio boolean DEFAULT false,
  completion_percentage integer DEFAULT 0 CHECK (completion_percentage >= 0 AND completion_percentage <= 100),
  started_at date,
  completed_at date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT projects_pkey PRIMARY KEY (id),
  CONSTRAINT projects_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT projects_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.promo_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code character varying NOT NULL UNIQUE,
  description text,
  discount_type character varying NOT NULL CHECK (discount_type::text = ANY (ARRAY['percentage'::character varying, 'fixed'::character varying]::text[])),
  discount_value numeric NOT NULL,
  min_purchase numeric DEFAULT 0,
  max_uses integer,
  current_uses integer DEFAULT 0,
  valid_from timestamp with time zone DEFAULT now(),
  valid_until timestamp with time zone,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT promo_codes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.quiz_leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  recommended_plan text,
  answers jsonb,
  scores jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quiz_leads_pkey PRIMARY KEY (id)
);
CREATE TABLE public.services (
  id integer NOT NULL DEFAULT nextval('services_id_seq'::regclass),
  name text NOT NULL UNIQUE,
  slug text NOT NULL UNIQUE,
  description text,
  short_description text,
  price numeric NOT NULL,
  price_type text DEFAULT 'fixed'::text CHECK (price_type = ANY (ARRAY['fixed'::text, 'starting_from'::text])),
  category text DEFAULT 'vitrine'::text CHECK (category = ANY (ARRAY['vitrine'::text, 'ecommerce'::text, 'surmesure'::text, 'maintenance'::text, 'addon'::text])),
  features jsonb DEFAULT '[]'::jsonb,
  max_pages integer,
  max_products integer,
  support_months integer DEFAULT 0,
  is_popular boolean DEFAULT false,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT services_pkey PRIMARY KEY (id)
);
CREATE TABLE public.settings (
  id integer NOT NULL DEFAULT nextval('settings_id_seq'::regclass),
  key text NOT NULL UNIQUE,
  value text,
  type text DEFAULT 'string'::text CHECK (type = ANY (ARRAY['string'::text, 'number'::text, 'boolean'::text, 'json'::text])),
  description text,
  is_public boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.testimonials (
  id integer NOT NULL DEFAULT nextval('testimonials_id_seq'::regclass),
  user_id uuid,
  client_name text NOT NULL,
  client_company text,
  client_role text,
  client_avatar text,
  content text NOT NULL,
  rating integer DEFAULT 5 CHECK (rating >= 1 AND rating <= 5),
  project_type text,
  is_featured boolean DEFAULT false,
  is_approved boolean DEFAULT false,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT testimonials_pkey PRIMARY KEY (id),
  CONSTRAINT testimonials_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
